I_am_title
CozlovschiNichita/Tekwill_FE_gr11 pull request #6
Opened 2024-03-22 22:50 UTC by CozlovschiNichita

# HMW Style DIsc
- выполнил все указанные в hmw стили в css;
- узнал больше о блочной системе в css;
- были небольшие трудности, но здесь нужно больше "играться" с тенями, и со свойствами Box Model.
<img width="918" alt="Снимок экрана 2024-03-23 в 00 36 24" src="https://github.com/CozlovschiNichita/Tekwill_FE_gr11/assets/161749799/a24f8c4d-2f83-4cb2-b14f-a7c64eb31eb0">

2024-03-23 08:57 UTC, dragan-andrei approved these changes
Very good!👍🥇😄

2024-03-25 17:36 UTC, IvanCeban requested changes
Great job!
No objections regarding the code quality.
As an improvement, can you achieve the same result with the HTML provided in homework task?

I mean without "circle" and "circle-1" divs

2024-03-25 19:36 UTC, CozlovschiNichita commented
@IvanCeban 
OK, I can do that

2024-03-25 20:08 UTC, CozlovschiNichita commented
# Corrected work
<img width="721" alt="Снимок экрана 2024-03-25 в 21 50 02" src="https://github.com/CozlovschiNichita/Tekwill_FE_gr11/assets/161749799/f53901e5-0263-4d73-b43e-5bc39fea7c53">

2024-03-28 17:08 UTC, merged